name: Build and lint

on:
    push:
        # TODO: enable lint/build jobs after Prisma env variable issue is fixed
        branches-ignore: "**"

jobs:
    lint:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - name: Setup Node
              uses: actions/setup-node@v2
              with:
                  node-version: "16"
                  cache: "yarn"
                  cache-dependency-path: ./yarn.lock
            - name: Install dependencies
              run: yarn install --frozen-lockfile
            - name: Generate types
              run: yarn generate
            - name: Run checks
              run: yarn ci-check

    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - name: Setup Node
              uses: actions/setup-node@v2
              with:
                  node-version: "16"
                  cache: "yarn"
                  cache-dependency-path: ./yarn.lock
            - name: Install dependencies
              run: yarn install --frozen-lockfile
            - name: Generate types
              run: yarn generate
            - name: Build project
              run: yarn build
